# Generated by Django 3.0 on 2022-07-27 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rsid_catalog", "0002_auto_20220727_0615"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notes",
        ),
        migrations.AlterField(
            model_name="rsids",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rsids",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
