# Generated by Django 3.0 on 2022-07-28 04:30

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("rsid_catalog", "0003_auto_20220727_1809"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rsids",
            name="diseases",
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name="rsids",
            name="gene",
            field=jsonfield.fields.JSONField(),
        ),
    ]
